# author is used in the atom feed
title: JBoss Developer Framework
author: JBoss Developer Framework
description: JBoss Developer Framework shows you how to write applications using JBoss technologies. Learn how to write an application suitable for mobile. Learn how to use the Java EE 6 API with JBoss AS. Learn how to add the power of CDI to your browser.
jira_key: JDF
ohloh_id: jboss-jdf
disqus: jdf
website_source_repo: https://github.com/jboss-jdf/jdf-site
irc_transcripts: http://transcripts.jboss.org/channel/irc.freenode.org/%23jboss-jdf/
version: 2.1.1.Final
profiles:
  development:
    base_url: http://localhost:4242
    minify: false
    google_plusone: false
    noindex: true
  sandbox:
    base_url: http://site-jdf.rhcloud.com
    minify: false
    google_plusone: false
    noindex: true
  production:
    base_url: http://jboss.org/jdf
    minify: true
    google_plusone: true
    google_analytics: UA-10656779-1
    noindex: false
  staging:
    base_url: http://jboss.org/jdf/staging
    minify: true
    google_plusone: false
    noindex: true
